#!/usr/bin/env sh
# Copy rice-omp's agent/ payload into the omp user config dir (default ~/.omp/agent).
# Only the files rice-omp owns are written; omp's own state (agent.db, sessions, .env) is untouched.
set -eu
src=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/agent
dest=${1:-"$HOME/.omp/agent"}
mkdir -p "$dest"

for item in APPEND_SYSTEM.md config.yml models.yml mcp.json agents skills mcp; do
	if [ -e "$dest/$item" ] && [ ! -e "$dest/$item.pre-rice" ]; then
		cp -a "$dest/$item" "$dest/$item.pre-rice"
	fi
	rm -rf "${dest:?}/$item"
	cp -a "$src/$item" "$dest/$item"
done
# Local build/dependency artifacts are regenerated by the MCP launchers on first run.
rm -rf "$dest/mcp/workflow/node_modules" "$dest/mcp/researcher-mcp/bin"

echo "Installed rice-omp into $dest" >&2
