#!/usr/bin/env sh
# Copy rice-omp's agent/ payload into the omp user config dir (default ~/.omp/agent).
# Only the files rice-omp owns are written; omp's own state (agent.db, sessions, .env) is untouched.
set -eu
src=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/agent
dest=${1:-"$HOME/.omp/agent"}
mkdir -p "$dest"
dest=$(CDPATH= cd -- "$dest" && pwd)

for item in APPEND_SYSTEM.md config.yml mcp.json agents skills extensions mcp; do
	if [ -e "$dest/$item" ] && [ ! -e "$dest/$item.pre-rice" ]; then
		cp -a "$dest/$item" "$dest/$item.pre-rice"
	fi
	rm -rf "${dest:?}/$item"
	cp -a "$src/$item" "$dest/$item"
done
# Local build/dependency artifacts are regenerated by the MCP launchers on first run.
rm -rf "$dest/mcp/workflow/node_modules" "$dest/mcp/researcher-mcp/bin"
# mcp.json launchers name the default agent dir; repoint them when installing elsewhere (e.g. a profile).
if [ "$dest" != "$HOME/.omp/agent" ]; then
	esc=$(printf '%s' "$dest" | sed 's/[|&\\]/\\&/g')
	sed "s|\${HOME}/\.omp/agent|$esc|g" "$src/mcp.json" >"$dest/mcp.json"
fi
# Superseded by extensions/cliproxyapi.ts; a leftover static `cpa` provider would shadow its discovery.
if [ -e "$dest/models.yml" ]; then
	[ -e "$dest/models.yml.pre-rice" ] || cp -a "$dest/models.yml" "$dest/models.yml.pre-rice"
	rm -f "$dest/models.yml"
fi

echo "Installed rice-omp into $dest" >&2
