#!/usr/bin/env sh
# Copy rice-omp's agent/ payload into the omp user config dir (default ~/.omp/agent).
# Only the files rice-omp owns are written; omp's own state (agent.db, sessions, .env) is untouched.
set -eu
src=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/agent
dest=${1:-"$HOME/.omp/agent"}
mkdir -p "$dest"
dest=$(CDPATH= cd -- "$dest" && pwd)
items='APPEND_SYSTEM.md config.yml mcp.json agents skills extensions mcp'

# Stage the exact payload first so local edits can be compared against what gets installed.
stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT
for item in $items; do cp -a "$src/$item" "$stage/$item"; done
# mcp.json launchers name the default agent dir; repoint them when installing elsewhere (e.g. a profile).
if [ "$dest" != "$HOME/.omp/agent" ]; then
	esc=$(printf '%s' "$dest" | sed 's/[|&\\]/\\&/g')
	sed "s|\${HOME}/\.omp/agent|$esc|g" "$src/mcp.json" >"$stage/mcp.json"
fi

# Copies of what this script last installed; drift = live file differs from that record,
# so ordinary repo changes are not mistaken for edits made outside the repo.
record="$dest/.rice-omp-installed"
mkdir -p "$record"
for item in $items; do
	if [ -e "$dest/$item" ]; then
		if [ ! -e "$dest/$item.pre-rice" ]; then
			cp -a "$dest/$item" "$dest/$item.pre-rice"
		elif [ -f "$dest/$item" ] && [ -f "$record/$item" ] && ! cmp -s "$record/$item" "$dest/$item"; then
			# Changed since the last install (omp /settings, ompweb, hand edits): keep it, show the drift.
			keep="$dest/$item.local-$(date +%Y%m%d-%H%M%S)"
			cp -a "$dest/$item" "$keep"
			echo "rice-omp: $item was changed outside the repo; saved as $keep. Changes being replaced:" >&2
			diff -u "$stage/$item" "$dest/$item" >&2 || true
		fi
	fi
	rm -rf "${dest:?}/$item"
	cp -a "$stage/$item" "$dest/$item"
	if [ -f "$stage/$item" ]; then cp -a "$stage/$item" "$record/$item"; fi
done
# Local build/dependency artifacts are regenerated by the MCP launchers on first run.
rm -rf "$dest/mcp/workflow/node_modules" "$dest/mcp/researcher-mcp/bin"
# Superseded by extensions/cliproxyapi.ts; a leftover static `cpa` provider would shadow its discovery.
if [ -e "$dest/models.yml" ]; then
	[ -e "$dest/models.yml.pre-rice" ] || cp -a "$dest/models.yml" "$dest/models.yml.pre-rice"
	rm -f "$dest/models.yml"
fi

echo "Installed rice-omp into $dest" >&2
